/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "functions-test.check" instead.
 */

#include <check.h>

#line 1 "functions-test.check"
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include "functions.h"

START_TEST(getEnvValTest)
{
#line 8
	char* systemPath;
	systemPath = getenv("PATH");

	fail_unless(strcmp(getEnvVal("PATH"), systemPath) == 0, "getEnvVal did not return same thing as getenv");
	fail_unless(strcmp(getEnvVal("path"), " ") == 0, "path without value did not return a space");

}
END_TEST

START_TEST(stringLengthTest)
{
#line 15
	int i;
	i = stringLength("test");

	fail_unless(i == 4, "did not return 4 for the word test");
	fail_unless(stringLength("") == 0, "did not return 0 for empty string");

}
END_TEST

START_TEST(stringCopyTest)
{
#line 22
	char* source;
	char* dest;
	source = "test";
	dest = stringCopy(source);

	fail_unless(strcmp(dest, source) == 0, "strcmp failed between dest and src");

	free(dest);
	dest = stringCopy("test");
	fail_unless(strcmp(dest, source) == 0, "strcmp failed between dest and src");

	free(dest);
	dest = stringCopy("");
	fail_unless(strcmp(dest, "") == 0, "strcmp failed between dest and an empty string");

}
END_TEST

START_TEST(readLineTest)
{
#line 38
	FILE* fp;
	fp = fopen("test.txt", "w");
	
	/* TEST INPUT 1 */
	char* rltest1;
	char* rltest1_expected;
	rltest1 = "this is a test\n";
	rltest1_expected = "this is a test";
	
	/* TEST INPUT 2 */
	char* rltest2;
	char* rltest2_expected;
	rltest2 = "this is a test\n";
	rltest2_expected = "this is a test";
	
	/* TEST INPUT 3 */
	char* rltest3;
	char* rltest3_expected;
	rltest3 = "this is a test dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\n";
	rltest3_expected = NULL;

	/* TEST INPUT 4 */
	char* rltest4;
	char* rltest4_expected;
	rltest4 = "this is a test\n";
	rltest4_expected = "this is a test";

	fwrite(rltest1, sizeof(char), stringLength(rltest1), fp);
	fwrite(rltest2, sizeof(char), stringLength(rltest2), fp);
	fwrite(rltest3, sizeof(char), stringLength(rltest3), fp);
	fwrite(rltest4, sizeof(char), stringLength(rltest4), fp);
	fclose(fp);
	
	char* line;
	int fileHandle;
	fileHandle = open("test.txt", O_RDONLY);
	fail_unless(fileHandle != -1, "test input file could not be opened");
	
	/* CHECK TEST 1 */
	line = readLine(fileHandle);
	printf("READLINE TEST1 expected value: %s\n", rltest1_expected);
	printf("READLINE TEST1 returned value: %s\n", line);
	fail_unless(strcmp(line, rltest1_expected) == 0, "TEST1 values did not match\n", rltest1_expected, line);
	printf("\n");

	/* CHECK TEST 2 */
	line = readLine(fileHandle);
	printf("READLINE TEST2 expected value: %s\n", rltest2_expected);
	printf("READLINE TEST2 returned value: %s\n\n", line);
	fail_unless(strcmp(line, rltest2_expected) == 0, "TEST2 values did not match\n", rltest2_expected, line);
	printf("\n");

	/* CHECK TEST 3 */
	line = readLine(fileHandle);
	printf("READLINE TEST3 expected value: %s\n", rltest3_expected);
	printf("READLINE TEST3 returned value: %s\n\n", line);
	fail_unless(line == rltest3_expected, "TEST3 values did not match\n", rltest3_expected, line);
	printf("\n");

	/* CHECK TEST 4 */
	line = readLine(fileHandle);
	printf("READLINE TEST4 expected value: %s\n", rltest4_expected);
	printf("READLINE TEST4 returned value: %s\n\n", line);
	fail_unless(strcmp(line, rltest4_expected) == 0, "TEST4 values did not match\n", rltest4_expected, line);
	printf("\n");

	/* CLEAN UP DATA */
	close(fileHandle);
	remove("test.txt");

}
END_TEST

START_TEST(parseLineTest1)
{
#line 109
	/* TEST INPUT 1 */
	char* pltest;
	pltest = "this is a test";
	char* pltest_expected;
	pltest_expected = "this is a test";

	char* parsed;

	/* CHECK INPUT 1 */
	parsed = parseLine(pltest);
	printf("input: %s\n", pltest);
	printf("PARSELINE TEST 1 expected value: %s\n", pltest_expected);
	printf("PARSELINE TEST 1 returned value: %s\n", parsed);
	fail_unless(strcmp(parsed, pltest_expected) == 0, "returned string was not the same as expected\n");
	printf("\n");

}
END_TEST

START_TEST(parseLineTest2)
{
#line 125
	/* TEST INPUT 2 */
	char* pltest;
	pltest = "$path";
	char* pltest_expected;
	pltest_expected = " ";

	char* parsed;

	/* CHECK INPUT 2 */
	parsed = parseLine(pltest);
	printf("input: %s\n", pltest);
	printf("PARSELINE TEST 2 expected value: %s\n", pltest_expected);
	printf("PARSELINE TEST 2 returned value: %s\n\n", parsed);
	fail_unless(strcmp(parsed, pltest_expected) == 0, "returned string was not the same as expected\n");
	
}
END_TEST

START_TEST(parseLineTest3)
{
#line 140
	/* TEST INPUT 3 */
	setenv("var", "new value", 0);
	fail_unless(strcmp(getEnvVal("var"), "new value") == 0, "setting environment variable failed in test setup");
	char* pltest;
	pltest = "$var";
	char* pltest_expected;
	pltest_expected = "new value";

	char* parsed;

	/* CHECK INPUT 3 */
	parsed = parseLine(pltest);
	printf("input: %s\n", pltest);
	printf("PARSELINE TEST 3 expected value: %s\n", pltest_expected);
	printf("PARSELINE TEST 3 returned value: %s\n\n", parsed);
	fail_unless(strcmp(parsed, pltest_expected) == 0, "returned string was not the same as expected\n");

}
END_TEST

START_TEST(parseLineTest4)
{
#line 157
	/* TEST INPUT 4 */
	char* pltest;
	pltest = "$PATH $PATH $PATH $PATH $PATH";
	char* pltest_expected;
	pltest_expected = NULL;

	char* parsed;

	/* CHECK INPUT 4 */
	parsed = parseLine(pltest);
	printf("input: %s\n", pltest);
	printf("PARSELINE TEST 4 expected value: %s\n", pltest_expected);
	printf("PARSELINE TEST 4 returned value: %s\n\n", parsed);
	fail_unless(parsed == pltest_expected, "returned string was not the same as expected\n");

}
END_TEST

START_TEST(parseLineTest5)
{
#line 172
	/* TEST INPUT 5 */
	char* pltest;
	pltest = "$PATH$PATH";
	char* pltest_expected;
	pltest_expected = " ";

	char* parsed;

	/* CHECK INPUT 5 */
	parsed = parseLine(pltest);
	printf("input: %s\n", pltest);
	printf("PARSELINE TEST 5 expected value: %s\n", pltest_expected);
	printf("PARSELINE TEST 5 returned value: %s\n\n", parsed);
	fail_unless(parsed == pltest_expected, "returned string was not the same as expected\n");

}
END_TEST

START_TEST(parseLineTest6)
{
#line 187
	/* TEST INPUT 6 */
	setenv("var", "new value", 0);
	fail_unless(strcmp(getEnvVal("var"), "new value") == 0, "setting environment variable failed in test setup");
	char* pltest;
	pltest = "$var ";
	char* pltest_expected;
	pltest_expected = "new value";

	char* parsed;

	/* CHECK INPUT 6 */
	parsed = parseLine(pltest);
	printf("input: %s\n", pltest);
	printf("PARSELINE TEST 6 expected value: %s\n", pltest_expected);
	printf("PARSELINE TEST 6 returned value: %s\n\n", parsed);
	fail_unless(strcmp(parsed, pltest_expected) == 0, "returned string was not the same as expected\n");



	


























}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, getEnvValTest);
    tcase_add_test(tc1_1, stringLengthTest);
    tcase_add_test(tc1_1, stringCopyTest);
    tcase_add_test(tc1_1, readLineTest);
    tcase_add_test(tc1_1, parseLineTest1);
    tcase_add_test(tc1_1, parseLineTest2);
    tcase_add_test(tc1_1, parseLineTest3);
    tcase_add_test(tc1_1, parseLineTest4);
    tcase_add_test(tc1_1, parseLineTest5);
    tcase_add_test(tc1_1, parseLineTest6);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
